book_review/authentication/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = "authentication"

urlpatterns = [
    path("sign-up/", views.sign_up, name="sign_up"),
    path("log-in/", LoginView.as_view(template_name="authentication/login.html"), name="login"),
    path("log-out/", LogoutView.as_view(), name="logout"),
]

book_review/config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("pages.urls")),
    path('review/', include("review.urls")),
    path("auth/", include("authentication.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

book_review/pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("library/", views.library, name="library"),
    path("books/", views.books, name="books"),
    path("book-detail/<int:book_id>/", views.book_detail, name="book_detail"),

]

book_review/review/urls.py
from django.urls import path

from . import views

app_name = "review"

urlpatterns = [
    path("create-review/<int:book_id>/", views.create_review, name="create_review"),
    path("edit-review/<int:review_id>/", views.edit_review, name="edit_review"),
    path("confirm-delete-review/<int:review_id>/", views.confirm_delete_review, name="confirm_delete_review"),
    path("delete-review/<int:review_id>/", views.delete_review, name="delete_review"),
]

book_review/authentication/models.py
from django.db import models

# Create your models here.

book_review/pages/models.py
from django.db import models

# Create your models here.

book_review/review/models.py
import os

from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from datetime import timedelta

from django.utils import timezone

User = get_user_model()

class Author(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    bio = models.TextField()
    year_of_birth = models.DateField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class GenreChoices(models.TextChoices):
    FANTASY = "FTSY", "Fantasy"
    SCI_FI = "SCIFI", "Science Fiction"
    MYSTERY_THRILLER = "MYST_THRILL", "Mystery/Thriller"
    ROMANCE = "ROM", "Romance" 
    HISTORICAL_FICTION = "HIST_FIC", "Historical Fiction"
    HORROR = "HORROR", "Horror"
    DYSTOPIAN = "DYST", "Dystopian"
    ADVENTURE = "ADVN", "Adventure"
    BIO_AUTOBIO = "BIO_AUTOBIO", "Biography/Autobiography"
    SELF_HELP = "SELF_HELP", "Self Help"
    HISTORY = "HIST", "History"
    SCIENCE = "SCI", "Science"
    BUSINESS = "BSNS", "Business"


def book_cover_upload_to(instance, filename):
    # Generate a shorter, more manageable file name
    _, ext = os.path.splitext(filename)
    return f"book_cover_images/{slugify(instance.title)}{ext}"

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    genre = models.CharField(max_length=11, choices=GenreChoices, default=GenreChoices.MYSTERY_THRILLER)
    publication_date = models.DateField()
    cover_image = models.ImageField(upload_to=book_cover_upload_to)
    isbn = models.CharField(max_length=255)
    number_of_pages = models.PositiveIntegerField()

    def __str__(self):
        return self.title

def validate_rating(rating):
    if rating < 1 or rating > 5:
        raise ValidationError("Rating must be between 1 and 5")

class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    review = models.TextField()
    rating = models.PositiveIntegerField(validators=[validate_rating])
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    added_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Review by {self.added_by} - {self.review[10]}"
    
    @property
    def is_within_edit_window(self):
        EDIT_WINDOW = 5
        time_difference = timezone.now() - self.added_on
        return time_difference < timedelta(minutes=EDIT_WINDOW)

book_review/review/forms.py
from django import forms

from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['book', 'review', 'rating', 'added_by']

book_review/authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

# Create your views here.
def sign_up(request):
    form = UserCreationForm()
    if request.method == "POST":
        print(request.POST)
        print(form)
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Account created successfully")
            return redirect("authentication:login")
    context = {"form": form}
    return render(request, "authentication/sign-up.html", context)

book_review/pages/views.py
from django.shortcuts import render, get_object_or_404

from review.models import Book, Review

# Create your views here.
def home(request):
    return render(request, "pages/home.html")

def about(request):
    return render(request, "pages/about.html")

def contact(request):
    return render(request, "pages/contact.html")

def library(request):
    return render(request, "pages/library.html")

def books(request):
    all_books = Book.objects.all()
    return render(request, "pages/books.html", {"books": all_books})

def book_detail(request, book_id):
    book =  get_object_or_404(Book, pk=book_id)
    reviews = Review.objects.filter(book=book)
    context = {
        "book": book,
        "reviews": reviews,
    }
    return render(request, "pages/book_detail.html", context)

book_review/review/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from review.models import Book, Review

from .forms import ReviewForm

@login_required
def create_review(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    form = ReviewForm()
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Review added successfully")
            # return redirect(reverse("pages:book_detail", args=[book_id]))
            return redirect("pages:book_detail", book_id)
    context = {"form": form, "book": book}
    return render(request, "review/create-review.html", context)

@login_required
def edit_review(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    book = review.book
    form = ReviewForm(instance=review)
    if request.user != review.added_by:
        messages.error(request, "You do not have permission to edit that review")
        return redirect("pages:books") 
    if request.method == "POST":
        if not review.is_within_edit_window:
            messages.error(request, "You can only edit a review 5 minutes after posting it")
            return redirect(reverse("pages:book_detail", args=[book.id]))
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            messages.success(request, "Review updated successfully")
            return redirect(reverse("pages:book_detail", args=[book.id]))
    context = {"form": form, "review": review, "book":book}
    return render(request, "review/edit-review.html", context)

@login_required
def confirm_delete_review(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    book = review.book
    if request.user != review.added_by:
        messages.error(request, "You do not have permission to edit that review")
        return redirect("pages:books") 
    context = {"review": review, "book":book}
    return render(request, "review/confirm-delete-review.html", context)

@login_required
def delete_review(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    book = review.book
    if request.user != review.added_by:
        messages.error(request, "You do not have permission to edit that review")
        return redirect("pages:books") 
    if request.method == "POST":
        review.delete()
        messages.success(request, "Review deleted successfully")
    return redirect(reverse("pages:book_detail", args=[book.id]))

    

    

book_review/templates/authentication/login.html
{% extends "partials/base.html" %}
{% load static %}

{% block body %}

<section class="authentication-container forms">
    <div class="form login">
        <div class="form-content">
            <header>Login</header>
            <form action="{% url 'authentication:login' %}" method="POST">
                {% csrf_token %}
                <div class="field input-field">
                    <input type="text" name="username" placeholder="Username" class="input">
                </div>

                <div class="field input-field">
                    <input name="password" type="password" placeholder="Password" class="password">
                    <i class='bx bx-hide eye-icon'></i>
                </div>

                <div class="form-link">
                    <a href="#" class="forgot-pass">Forgot password?</a>
                </div>

                <div class="field button-field">
                    <button type="submit">Login</button>
                </div>
            </form>

            <div class="form-link">
                <span>Don't have an account? <a href="{% url 'authentication:sign_up' %}" class="link signup-link">Signup</a></span>
            </div>
        </div>

        <div class="line"></div>

        <div class="media-options">
            <a href="#" class="field facebook">
                <i class='bx bxl-facebook facebook-icon'></i>
                <span>Login with Facebook</span>
            </a>
        </div>

        <div class="media-options">
            <a href="#" class="field google">
                <img src="{% static 'images/google.png' %}" alt="" class="google-img">
                <span>Login with Google</span>
            </a>
        </div>

    </div>
</section>
{% endblock body %}

book_review/templates/authentication/sign-up.html
{% extends "partials/base.html" %}
{% load static %}

{% block body %}


<section class="authentication-container forms">

    <!-- Signup Form -->

    <div class="form signup">
        <div class="form-content">
            <header>Signup</header>
            <form action="{% url 'authentication:sign_up' %}" method="POST">
                {% csrf_token %}
                <div>
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                    <p class="field-error">{{ error }}</p>
                    {% endfor %}                
                {% else %}
                {% endif %}
                </div>
                <div class="field input-field">
                    {% if form.username.errors %}
                        {% for error in form.username.errors %}
                        <p class="field-error">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <input name="username" type="text" placeholder="Username" class="input" {% if form.username.value %}value="{{ form.username.value }}"{% endif %}>
                </div>

                <div class="field input-field">
                    {% if form.password1.errors %}
                        {% for error in form.password1.errors %}
                        <p class="field-error">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <input name="password1" type="password" placeholder="Create password" class="password">
                </div>

                <div class="field input-field">
                    {% if form.password2.errors %}
                        {% for error in form.password2.errors %}
                        <p class="field-error">{{ error }}</p>
                        {% endfor %}
                    {% endif %}
                    <input name="password2" type="password" placeholder="Confirm password" class="password">
                    <i class='bx bx-hide eye-icon'></i>
                </div>

                <div class="field button-field">
                    <button type="submit">Signup</button>
                </div>
            </form>

            <div class="form-link">
                <span>Already have an account? <a href="{% url 'authentication:login' %}" class="link login-link">Login</a></span>
            </div>
        </div>

        <div class="line"></div>

        <div class="media-options">
            <a href="#" class="field facebook">
                <i class='bx bxl-facebook facebook-icon'></i>
                <span>Login with Facebook</span>
            </a>
        </div>

        <div class="media-options">
            <a href="#" class="field google">
                <img src="{% static 'images/google.png' %}" alt="" class="google-img">
                <span>Login with Google</span>
            </a>
        </div>

    </div>
</section>

{% endblock body %}

book_review/templates/partials/mini-contact.html
{% load static %}



{% block body %}
<!-- Contact -->
<div class="Contact">
    <div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="titlepage3">
                <h2>Contact</h2>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
            <form>
                <div class="row">
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-12">
                    <input class="form-control" placeholder="Name" type="Name">
                </div>
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-12">
                    <input class="form-control" placeholder="Phone Number" type="Phone Number">
                </div>
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-12">
                    <input class="form-control" placeholder="Email" type="Email">
                </div>
                <div class="col-xl-3 col-lg-3 col-md-3 col-sm-12">
                    <textarea class="textarea" placeholder="Message">Message</textarea>
                </div>
                </div>
            </form>
        </div>
        <button class="send-btn">Send</button>
    </div>
    </div>
</div>
<!-- end Contact -->
{% endblock body %}

book_review/templates/partials/mini-library.html
{% load static %}


{% block body %}
<!-- Library -->
<div class="Library">
    <div class="container">
    <div class="row">
        <div class="col-md-10 offset-md-1">
            <div class="titlepage">
                <h2>Our <strong class="black">Library </strong></h2>
                <span>adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris</span> 
            </div>
        </div>
    </div>
    </div>
    <div class="bg">
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-md-1">
                <div class="Library-box">
                <figure><img src="{% static 'images/Library-.jpg' %}" alt="#"/></figure>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="read-more">
                <a href="#">Read More</a>
            </div>
        </div>
    </div>
    </div>
</div>
<!-- end Library -->
{% endblock body %}

book_review/templates/partials/review.html
{% csrf_token %}
<h2 class="review-heading">{{ heading }} for {{ book.title }}</h2>
{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
    <p class="field-error">{{ error }}</p>
    {% endfor %}        
{% endif %}
{% if form.book.errors %}
    {% for error in form.book.errors %}
    <p class="field-error">{{ error }}</p>
    {% endfor %}        
{% endif %}
<input type="hidden" name="book" value="{{ book.id }}">
{% if form.added_by.errors %}
    {% for error in form.added_by.errors %}
    <p class="field-error">{{ error }}</p>
    {% endfor %}        
{% endif %}
<input type="hidden" name="added_by" value="{{ request.user.id }}">
{% if form.review.errors %}
    {% for error in form.review.errors %}
    <p class="field-error">{{ error }}</p>
    {% endfor %}        
{% endif %}
<textarea name="review" rows="8" placeholder="What did you think about {{ book.title }}?">{% if form.review.value %}{{ form.review.value }}{% endif %}</textarea>
{% if form.rating.errors %}
    {% for error in form.rating.errors %}
    <p class="field-error">{{ error }}</p>
    {% endfor %}        
{% endif %}
<input type="number" name="rating" placeholder="Rating" {% if form.rating.value %}value="{{ form.rating.value }}"{% endif %}><br>
<input type="submit" value="Submit" id="send"><br>